def register(add_entry):
    # -------------------------------------------------------------
    # 1. TRAVEL -> tourism.json (22 entries)
    # -------------------------------------------------------------
    travel = [
        {"id": "ru:bilet:noun", "word": "билет", "form": "noun", "theme": "tourism", "transcription": "[bʲɪˈlʲet]", "gender": "masculine", "countability": "countable", "plural_form": "билеты", "emoji": "🎫", "no_antonym": True, "definitions": ["Документ, который даёт право на проезд в транспорте."], "examples": ["Пассажир купил новый билет на поезд в кассе вокзала."]},
        {"id": "ru:pasport:noun", "word": "паспорт", "form": "noun", "theme": "tourism", "transcription": "[ˈpaspərt]", "gender": "masculine", "countability": "countable", "plural_form": "паспорта", "emoji": "🛂", "no_antonym": True, "definitions": ["Официальный документ, подтверждающий личность человека за границей."], "examples": ["Турист показывает свой заграничный паспорт на таможне в аэропорту."]},
        {"id": "ru:chemodan:noun", "word": "чемодан", "form": "noun", "theme": "tourism", "transcription": "[tɕɪmɐˈdan]", "gender": "masculine", "countability": "countable", "plural_form": "чемоданы", "emoji": "🧳", "no_antonym": True, "definitions": ["Большая дорожная сумка с ручкой для перевозки одежды."], "examples": ["Путешественник несёт тяжёлый чемодан на платформу к поезд."]},
        {"id": "ru:puteshestviye:noun", "word": "путешествие", "form": "noun", "theme": "tourism", "transcription": "[pʊtʲɪˈʂestvʲɪjə]", "gender": "neuter", "countability": "countable", "plural_form": "путешествия", "emoji": "✈️", "no_antonym": True, "definitions": ["Поездка или передвижение по дальним странам и городам."], "examples": ["Наше интересное путешествие по европейским городам продолжалось месяц."]},
        {"id": "ru:bronirovanie:noun", "word": "бронирование", "form": "noun", "theme": "tourism", "transcription": "[brənʲɪˈrovənʲɪjə]", "gender": "neuter", "countability": "countable", "plural_form": "бронирования", "emoji": "📅", "no_antonym": True, "definitions": ["Предварительный заказ номера в отеле или билета."], "examples": ["Мы подтвердили бронирование уютного номера в гостинице через интернет."]},
        {"id": "ru:napravleniye:noun", "word": "направление", "form": "noun", "theme": "tourism", "transcription": "[nəprɐˈvlʲenʲɪjə]", "gender": "neuter", "countability": "countable", "plural_form": "направления", "emoji": "🧭", "no_antonym": True, "definitions": ["Линия движения к определенному объекту или городу."], "examples": ["Турист выбрал южное направление для своего летнего отдыха."]},
        {"id": "ru:pryamo:adverb", "word": "прямо", "form": "adverb", "theme": "tourism", "transcription": "[ˈprʲamə]", "emoji": "⬆️", "antonyms": ["назад"], "definitions": ["В ровном направлении без поворотов в стороны."], "examples": ["Идите прямо по этой широкой улице до центрального парка."]},
        {"id": "ru:povorachivat:verb", "word": "поворачивать", "form": "verb", "theme": "tourism", "transcription": "[pəvɐˈratɕɪvətʲ]", "emoji": "🔄", "no_antonym": True, "definitions": ["Изменять направление своего движения при ходьбе."], "examples": ["На перекрёстке вам нужно поворачивать направо к площади."]},
        {"id": "ru:povernut:verb", "word": "повернуть", "form": "verb", "theme": "tourism", "transcription": "[pəvʲɪrˈnutʲ]", "emoji": "↪️", "no_antonym": True, "definitions": ["Совершить один поворот в сторону при движении."], "examples": ["Водитель сумел быстро повернуть налево у старого светофора."]},
        {"id": "ru:sever:noun", "word": "север", "form": "noun", "theme": "tourism", "transcription": "[ˈsʲevʲɪr]", "gender": "masculine", "countability": "uncountable", "emoji": "🧭", "antonyms": ["юг"], "definitions": ["Сторона света, противоположная югу и тёплым странам."], "examples": ["Перелётные птицы улетают на холодный север весной."]},
        {"id": "ru:yug:noun", "word": "юг", "form": "noun", "theme": "tourism", "transcription": "[juk]", "gender": "masculine", "countability": "uncountable", "emoji": "☀️", "antonyms": ["север"], "definitions": ["Сторона света, противоположная северу, где тепло."], "examples": ["Летом многие люди едут отдыхать на тёплый юг."]},
        {"id": "ru:vostok:noun", "word": "восток", "form": "noun", "theme": "tourism", "transcription": "[vɐsˈtok]", "gender": "masculine", "countability": "uncountable", "emoji": "🌅", "antonyms": ["запад"], "definitions": ["Сторона света, где каждое утро восходит солнце."], "examples": ["Солнце медленно встаёт на востоке ранним летним утром."]},
        {"id": "ru:zapad:noun", "word": "запад", "form": "noun", "theme": "tourism", "transcription": "[ˈzapət]", "gender": "masculine", "countability": "uncountable", "emoji": "🌇", "antonyms": ["восток"], "definitions": ["Сторона света, где вечером заходит яркое солнце."], "examples": ["Солнце красиво садится на западе поздним тёплым вечером."]},
        {"id": "ru:bagazh:noun", "word": "багаж", "form": "noun", "theme": "tourism", "transcription": "[bɐˈɡaʂ]", "gender": "masculine", "countability": "uncountable", "emoji": "🧳", "no_antonym": True, "definitions": ["Вещи и сумки пассажира, перевозимые в поезде."], "examples": ["Пассажир сдал свой тяжелый багаж при регистрации на рейс."]},
        {"id": "ru:granitsa:noun", "word": "граница", "form": "noun", "theme": "tourism", "transcription": "[ɡrɐˈnʲitsə]", "gender": "feminine", "countability": "countable", "plural_form": "границы", "emoji": "🚧", "no_antonym": True, "definitions": ["Условная линия, разделяющая территории двух стран."], "examples": ["Автобус успешно пересёк государственную границу между двумя странами."]},
        {"id": "ru:turist:noun", "word": "турист", "form": "noun", "theme": "tourism", "transcription": "[tʊˈrʲist]", "gender": "masculine", "countability": "countable", "plural_form": "туристы", "emoji": "🧳", "no_antonym": True, "definitions": ["Человек, который путешествует по городам в отпуске."], "examples": ["Иностранный турист внимательно рассматривает карту старого города."]},
        {"id": "ru:gid:noun", "word": "гид", "form": "noun", "theme": "tourism", "transcription": "[ɡʲit]", "gender": "masculine", "countability": "countable", "plural_form": "гиды", "emoji": "🧑‍🏫", "no_antonym": True, "definitions": ["Экскурсовод, показывющий достопримечательности туристам."], "examples": ["Опытный гид рассказывает интересную историю старого красивого замка."]},
        {"id": "ru:platforma:noun", "word": "платформа", "form": "noun", "theme": "tourism", "transcription": "[plətˈformə]", "gender": "feminine", "countability": "countable", "plural_form": "платформы", "emoji": "🚉", "no_antonym": True, "definitions": ["Помост вдоль железнодорожных путей для посадки."], "examples": ["Пассажирский поезд прибывает на вторую платформу железнодорожного вокзала."]},
        {"id": "ru:reis:noun", "word": "рейс", "form": "noun", "theme": "tourism", "transcription": "[rʲejs]", "gender": "masculine", "countability": "countable", "plural_form": "рейсы", "emoji": "✈️", "no_antonym": True, "definitions": ["Поездка по маршруту самолёта или корабля."], "examples": ["Наш прямой рейс в столицу отправляется точно по расписанию."]},
        {"id": "ru:zaderzhka:noun", "word": "задержка", "form": "noun", "theme": "tourism", "transcription": "[zɐˈdʲerʂkə]", "gender": "feminine", "countability": "countable", "plural_form": "задержки", "emoji": "⏳", "no_antonym": True, "definitions": ["Опоздание рейса по времени от графика."], "examples": ["Задержка самолёта произошла из-за сильного тумана над городом."]},
        {"id": "ru:tamozhnya:noun", "word": "таможня", "form": "noun", "theme": "tourism", "transcription": "[tɐˈmoʐnʲə]", "gender": "feminine", "countability": "countable", "plural_form": "таможни", "emoji": "🛃", "no_antonym": True, "definitions": ["Государственное учреждение для контроля багажа на границе."], "examples": ["Все пассажиры быстро прошли таможню в международном аэропорту."]},
        {"id": "ru:viza:noun", "word": "виза", "form": "noun", "theme": "tourism", "transcription": "[ˈvʲizə]", "gender": "feminine", "countability": "countable", "plural_form": "визы", "emoji": "📄", "no_antonym": True, "definitions": ["Разрешение на въезд и пребывание в иностранном государстве."], "examples": ["Турист получил новую туристическую визу в консульстве вчера."]},
        {"id": "ru:za-granitsei:phrase", "word": "за границей", "form": "phrase", "theme": "tourism", "transcription": "[zə ɡrɐˈnʲitsɪj]", "emoji": "🌍", "no_antonym": True, "definitions": ["В другой иностранной стране за пределами родины."], "examples": ["Моя старшая сестра учится и работает сейчас за границей."]}
    ]
    for e in travel:
        # Fix count for чемодан example if needed
        if e['id'] == 'ru:chemodan:noun':
            e['examples'] = ["Путешественник несёт тяжёлый чемодан на платформу вокзала."]
        add_entry("tourism.json", e)

    # -------------------------------------------------------------
    # 2. SHOPPING -> shopping.json (24 entries)
    # -------------------------------------------------------------
    shopping = [
        {"id": "ru:stoit:verb", "word": "стоить", "form": "verb", "theme": "shopping", "transcription": "[ˈstoɪtʲ]", "emoji": "🏷️", "no_antonym": True, "definitions": ["Иметь определённую цену в магазине за товар."], "examples": ["Сколько может стоить эта новая кожаная сумка в магазине?"]},
        {"id": "ru:dorogoi:adjective", "word": "дорогой", "form": "adjective", "theme": "shopping", "transcription": "[dərɐˈɡoj]", "emoji": "💎", "antonyms": ["дешёвый"], "definitions": ["Имеющий высокую цену, стоящий больших денег."], "examples": ["Отец купил дорогой новый автомобиль в автосалоне города."]},
        {"id": "ru:deshyovyi:adjective", "word": "дешёвый", "form": "adjective", "theme": "shopping", "transcription": "[dʲɪˈʂovɨj]", "emoji": "🏷️", "antonyms": ["дорогой"], "definitions": ["Имеющий низкую цену, доступную для всех."], "examples": ["На распродаже продавали дешёвые свежие фрукты и овощи."]},
        {"id": "ru:nalichnye:noun", "word": "наличные", "form": "noun", "theme": "shopping", "transcription": "[nɐˈlʲitɕnɨjə]", "gender": "masculine", "countability": "pluralia_tantum", "emoji": "💵", "antonyms": ["карта"], "definitions": ["Бумажные деньги и монеты на руках."], "examples": ["Покупатель достал наличные деньги для оплаты покупки у кассы."]},
        {"id": "ru:kreditnaya-karta:noun", "word": "кредитная карта", "form": "noun", "theme": "shopping", "transcription": "[krʲɪˈdʲitnəjə ˈkartə]", "gender": "feminine", "countability": "countable", "plural_form": "кредитные карты", "emoji": "💳", "no_antonym": True, "definitions": ["Пластиковая банковская карта для безналичной оплаты."], "examples": ["Я заплатил за обед банковской кредитной картой в ресторане."]},
        {"id": "ru:chek:noun", "word": "чек", "form": "noun", "theme": "shopping", "transcription": "[tɕek]", "gender": "masculine", "countability": "countable", "plural_form": "чеки", "emoji": "🧾", "no_antonym": True, "definitions": ["Бумажный документ из кассы, подтверждающий оплату."], "examples": ["Кассир выдал мне кассовый чек после оплаты покупки."]},
        {"id": "ru:razmer:noun", "word": "размер", "form": "noun", "theme": "shopping", "transcription": "[rɐzˈmʲer]", "gender": "masculine", "countability": "countable", "plural_form": "размеры", "emoji": "📏", "no_antonym": True, "definitions": ["Величина одежды или обуви по стандартам."], "examples": ["Мне нужен сорок второй размер этих осенних кожаных ботинок."]},
        {"id": "ru:skidka:noun", "word": "скидка", "form": "noun", "theme": "shopping", "transcription": "[ˈskʲitkə]", "gender": "feminine", "countability": "countable", "plural_form": "скидки", "emoji": "🏷️", "no_antonym": True, "definitions": ["Снижение обычной цены товара на определённый процент."], "examples": ["На эти зимние куртки сегодня действует хорошая скидка."]},
        {"id": "ru:rasprodazha:noun", "word": "распродажа", "form": "noun", "theme": "shopping", "transcription": "[rəsprɐˈdaʐə]", "gender": "feminine", "countability": "countable", "plural_form": "распродажи", "emoji": "🛍️", "no_antonym": True, "definitions": ["Торговля товарами по сниженным сниженным ценам."], "examples": ["Большая сезонная распродажа началась в торговом центре вчера."]},
        {"id": "ru:kassir:noun", "word": "кассир", "form": "noun", "theme": "shopping", "transcription": "[kɐˈsʲir]", "gender": "masculine", "countability": "countable", "plural_form": "кассиры", "emoji": "🧑‍💼", "no_antonym": True, "definitions": ["Работник магазина, принимающий деньги за товар."], "examples": ["Вежливый кассир быстро пробил наши продукты в кассе."]},
        {"id": "ru:telezhka:noun", "word": "тележка", "form": "noun", "theme": "shopping", "transcription": "[tʲɪˈlʲeʂkə]", "gender": "feminine", "countability": "countable", "plural_form": "тележки", "emoji": "🛒", "no_antonym": True, "definitions": ["Корзина на колёсиках для продуктов в супермаркете."], "examples": ["Покупатель покатил полную тележку с продуктами к кассе."]},
        {"id": "ru:koshelyok:noun", "word": "кошелёк", "form": "noun", "theme": "shopping", "transcription": "[kəʂɨˈlʲok]", "gender": "masculine", "countability": "countable", "plural_form": "кошельки", "emoji": "👛", "no_antonym": True, "definitions": ["Карманная сумочка для хранения денег и карт."], "examples": ["Она положила сдачу в свой новый кожаный кошелёк."]},
        {"id": "ru:sdacha:noun", "word": "сдача", "form": "noun", "theme": "shopping", "transcription": "[ˈzdatɕə]", "gender": "feminine", "countability": "uncountable", "emoji": "🪙", "no_antonym": True, "definitions": ["Деньги, возвращаемые покупателю с большей суммы."], "examples": ["Кассир вернул мне сдачу бумажными купюрами и монетами."]},
        {"id": "ru:kupyura:noun", "word": "купюра", "form": "noun", "theme": "shopping", "transcription": "[kʊˈpʲurə]", "gender": "feminine", "countability": "countable", "plural_form": "купюры", "emoji": "💵", "no_antonym": True, "definitions": ["Бумажный денежный знак определённого номинала."], "examples": ["Покупатель дал кассиру сторублёвую бумажную купюру за хлеб."]},
        {"id": "ru:moneta:noun", "word": "монета", "form": "noun", "theme": "shopping", "transcription": "[mɐˈnʲetə]", "gender": "feminine", "countability": "countable", "plural_form": "монеты", "emoji": "🪙", "no_antonym": True, "definitions": ["Металлический денежный знак чеканной формы."], "examples": ["Мальчик нашел старую блестящую монету на улице вчера."]},
        {"id": "ru:primeryat:verb", "word": "примерять", "form": "verb", "theme": "shopping", "transcription": "[prʲɪmʲɪˈrʲatʲ]", "emoji": "👗", "no_antonym": True, "definitions": ["Надевать одежду для проверки размера перед покупкой."], "examples": ["Девочка начала примерять красивое красное платье перед зеркалом."]},
        {"id": "ru:primerit:verb", "word": "примерить", "form": "verb", "theme": "shopping", "transcription": "[prʲɪˈmʲerʲɪtʲ]", "emoji": "👠", "no_antonym": True, "definitions": ["Примерить один раз одежду в кабинке."], "examples": ["Я хочу примерить эти синие джинсы в при Before покупкой."]},
        {"id": "ru:platit-nalichnymi:phrase", "word": "платить наличными", "form": "phrase", "theme": "shopping", "transcription": "[plɐˈtʲitʲ nɐˈlʲitɕnɨmʲɪ]", "emoji": "💵", "no_antonym": True, "definitions": ["Рассчитываться за товар бумажными деньгами у кассы."], "examples": ["Многие покупатели предпочитают платить наличными деньгами в магазине."]},
        {"id": "ru:prodavets:noun", "word": "продавец", "form": "noun", "theme": "shopping", "transcription": "[prədɐˈvʲets]", "gender": "masculine", "countability": "countable", "plural_form": "продавцы", "emoji": "🧑‍💼", "antonyms": ["покупатель"], "definitions": ["Работник магазина, продающий товары покупателям."], "examples": ["Опытный продавец помог мне выбрать хорошую зимнюю куртку."]},
        {"id": "ru:klient:noun", "word": "клиент", "form": "noun", "theme": "shopping", "transcription": "[klʲɪˈjent]", "gender": "masculine", "countability": "countable", "plural_form": "клиенты", "emoji": "👤", "no_antonym": True, "definitions": ["Покупатель или заказчик услуг компании."], "examples": ["Довольный клиент благодаря продавцу оставил хороший отзыв за работу."]},
        {"id": "ru:torgovyi-tsentr:noun", "word": "торговый центр", "form": "noun", "theme": "shopping", "transcription": "[tɐrˈɡovɨj tsentr]", "gender": "masculine", "countability": "countable", "plural_form": "торговые центры", "emoji": "🏢", "no_antonym": True, "definitions": ["Большое здание со множеством магазинов и кафе."], "examples": ["В выходные дни весь город ходит в новый торговый центр."]},
        {"id": "ru:pekarnya:noun", "word": "пекарня", "form": "noun", "theme": "shopping", "transcription": "[pʲɪˈkarɳə]", "gender": "feminine", "countability": "countable", "plural_form": "пекарни", "emoji": "🥖", "no_antonym": True, "definitions": ["Заведение, где выпекают и продают свежий хлеб."], "examples": ["Утром из нашей местной пекарни пахнет свежим хлебом."]},
        {"id": "ru:apteka:noun", "word": "аптека", "form": "noun", "theme": "shopping", "transcription": "[ɐpˈtʲekə]", "gender": "feminine", "countability": "countable", "plural_form": "аптеки", "emoji": "💊", "no_antonym": True, "definitions": ["Учреждение, где продают лекарства и медикаменты."], "examples": ["Мама пошла в круглосуточную аптеку за нужными лекарствами."]},
        {"id": "ru:supermarket:noun", "word": "супермаркет", "form": "noun", "theme": "shopping", "transcription": "[sʊpʲɪrˈmarkʲɪt]", "gender": "masculine", "countability": "countable", "plural_form": "супермаркеты", "emoji": "🛒", "no_antonym": True, "definitions": ["Крупный магазин самообслуживания с широким выбором продуктов."], "examples": ["Мы ежедневно покупаем свежие продукты в большом супермаркете."] +
        [] # extra line handle
        }
    ]
    for e in shopping:
        if e['id'] == 'ru:rasprodazha:noun':
            e['definitions'] = ["Торговля товарами по сниженным ценам."]
        if e['id'] == 'ru:primerit:verb':
            e['examples'] = ["Я хочу примерить эти синие джинсы перед покупкой."]
        add_entry("shopping.json", e)

    # -------------------------------------------------------------
    # 3. HEALTH -> health.json (20 entries)
    # -------------------------------------------------------------
    health = [
        {"id": "ru:bol:noun", "word": "боль", "form": "noun", "theme": "health", "transcription": "[bolʲ]", "gender": "feminine", "countability": "countable", "plural_form": "боли", "emoji": "🩹", "no_antonym": True, "definitions": ["Неприятное физическое ощущение в теле при болезни."], "examples": ["Пациент чувствует сильную боль в правой руке сегодня."]},
        {"id": "ru:temperatura:noun", "word": "температура", "form": "noun", "theme": "health", "transcription": "[tʲɪmpʲɪrɐˈturə]", "gender": "feminine", "countability": "countable", "plural_form": "температуры", "emoji": "🌡️", "no_antonym": True, "definitions": ["Степень нагрева тела человека при заболевании."], "examples": ["У больного ребенка поднялась высокая температура сегодня вечером."]},
        {"id": "ru:golovnaya-bol:noun", "word": "головная боль", "form": "noun", "theme": "health", "transcription": "[ɡəlɐvˈnajə bolʲ]", "gender": "feminine", "countability": "countable", "plural_form": "головные боли", "emoji": "🤯", "no_antonym": True, "definitions": ["Боль в области головы при утомлении."], "examples": ["Сильная головная боль мешает мне работать за компьютером."]},
        {"id": "ru:kashel:noun", "word": "кашель", "form": "noun", "theme": "health", "transcription": "[ˈkaʂɨlʲ]", "gender": "masculine", "countability": "uncountable", "emoji": "😷", "no_antonym": True, "definitions": ["Резкий выдох при раздражении дыхательных путей."], "examples": ["Ученик пропустил уроки из-за сильного кашля сегодня."]},
        {"id": "ru:prostuda:noun", "word": "простуда", "form": "noun", "theme": "health", "transcription": "[prɐˈstudə]", "gender": "feminine", "countability": "countable", "plural_form": "простуды", "emoji": "🤧", "no_antonym": True, "definitions": ["Инфекционное заболевание от сильного охлаждения тела."], "examples": ["Осенью многие люди болеют неприятной частой простудой."]},
        {"id": "ru:lekarstvo:noun", "word": "лекарство", "form": "noun", "theme": "health", "transcription": "[lʲɪˈkarstvə]", "gender": "neuter", "countability": "countable", "plural_form": "лекарства", "emoji": "💊", "no_antonym": True, "definitions": ["Медицинское средство для лечения и выздоровления."], "examples": ["Врач выписал больному эффективное новое лекарство сегодня."]},
        {"id": "ru:tabletka:noun", "word": "таблетка", "form": "noun", "theme": "health", "transcription": "[tɐˈblʲetkə]", "gender": "feminine", "countability": "countable", "plural_form": "таблетки", "emoji": "💊", "no_antonym": True, "definitions": ["Прессованная твердая форма лекарственного препарата."], "examples": ["Брат выпил одну белую таблетку от головной боли."]},
        {"id": "ru:travma:noun", "word": "травма", "form": "noun", "theme": "health", "transcription": "[ˈtravmə]", "gender": "feminine", "countability": "countable", "plural_form": "травмы", "emoji": "🩹", "no_antonym": True, "definitions": ["Повреждение органов или тканей при падении."], "examples": ["Спортсмен получил опасную травму ноги во время матча."]},
        {"id": "ru:skoraya-pomoshch:noun", "word": "скорая помощь", "form": "noun", "theme": "health", "transcription": "[ˈskərəjə ˈpoməɕː]", "gender": "feminine", "countability": "uncountable", "emoji": "🚑", "no_antonym": True, "definitions": ["Служба экстренной медицинской помощи при несчастье."], "examples": ["Машина скорой помощи быстро приехала на вызов вчера."]},
        {"id": "ru:priyom:noun", "word": "приём", "form": "noun", "theme": "health", "transcription": "[prʲɪˈjom]", "gender": "masculine", "countability": "countable", "plural_form": "приёмы", "emoji": "👨‍⚕️", "no_antonym": True, "definitions": ["Встреча врача с пациентом в больнице."], "examples": ["Я записался на приём к опытному врачу утром."]},
        {"id": "ru:zabolet:verb", "word": "заболеть", "form": "verb", "theme": "health", "transcription": "[zəbɐˈlʲetʲ]", "emoji": "🤒", "antonyms": ["выздороветь"], "definitions": ["Стать больным, заразиться вирусной инфекцией."], "examples": ["Зимой очень легко заболеть от сильного холодного ветра."]},
        {"id": "ru:vyzdoravlivat:verb", "word": "выздоравливать", "form": "verb", "theme": "health", "transcription": "[vɨzdəˈravlʲɪvətʲ]", "emoji": "💪", "antonyms": ["заболевать"], "definitions": ["Восстанавливать своё здоровье после перенесенной болезни."], "examples": ["После приёма лекарств больной начал быстро выздоравливать."]},
        {"id": "ru:beremennaya:adjective", "word": "беременная", "form": "adjective", "theme": "health", "transcription": "[bʲɪˈrʲemʲɪnːəjə]", "emoji": "🤰", "no_antonym": True, "definitions": ["Женщина, носящая плод в своем чреве."], "examples": ["Беременная женщина пришла на приём в медицинский центр."]},
        {"id": "ru:allergiya:noun", "word": "аллергия", "form": "noun", "theme": "health", "transcription": "[ɐlʲɪrˈɡʲijə]", "gender": "feminine", "countability": "uncountable", "emoji": "🤧", "no_antonym": True, "definitions": ["Повышенная чувствительность организма к раздражителям."], "examples": ["У мальчика сильная аллергия на весеннее цветение растений."]},
        {"id": "ru:dieta:noun", "word": "диета", "form": "noun", "theme": "health", "transcription": "[dʲɪˈjetə]", "gender": "feminine", "countability": "countable", "plural_form": "диеты", "emoji": "🥗", "no_antonym": True, "definitions": ["Специальный режим питания из полезных продуктов."], "examples": ["Строгая правильная диета помогает человеку восстановить своё здоровье."]},
        {"id": "ru:ves:noun", "word": "вес", "form": "noun", "theme": "health", "transcription": "[vʲes]", "gender": "masculine", "countability": "uncountable", "emoji": "⚖️", "no_antonym": True, "definitions": ["Масса тела человека в килограммах."], "examples": ["Спортсмен каждый день проверяет свой точный вес."]},
        {"id": "ru:krov:noun", "word": "кровь", "form": "noun", "theme": "health", "transcription": "[krofʲ]", "gender": "feminine", "countability": "uncountable", "emoji": "🩸", "no_antonym": True, "definitions": ["Красная жидкость, циркулирующая в организме человека."], "examples": ["Врач взял у пациента кровь для проведения анализа."]},
        {"id": "ru:stomatolog:noun", "word": "стоматолог", "form": "noun", "theme": "health", "transcription": "[stəmətˈolək]", "gender": "masculine", "countability": "countable", "plural_form": "стоматологи", "emoji": "🦷", "no_antonym": True, "definitions": ["Врач, специализирующийся на лечении зубов."], "examples": ["Опытный стоматолог безболезненно вылечил мне заболевший зуб."]},
        {"id": "ru:bolet:verb", "word": "болеть", "form": "verb", "theme": "health", "transcription": "[bɐˈlʲetʲ]", "emoji": "🤕", "no_antonym": True, "definitions": ["Испытывать болевые ощущения в теле."], "examples": ["У меня сильно болит зубы после сладкого пирожного."]}
    ]
    for e in health:
        if e['id'] == 'ru:bolet:verb':
            e['examples'] = ["У меня сильно болят зубы после сладкого пирожного."]
        add_entry("health.json", e)
