module.exports = {
  colors: [
    { id: 'el:aspro:adjective', word: 'άσπρος', language: 'el', form: 'adjective', level: 'A1', transcription: '/ˈaspros/', emoji: '⚪', definitions: ['που έχει το χρώμα του χιονιού'], examples: ['Το σπίτι έχει άσπρο χρώμα.'], domain: 'general', theme: 'colors', updated: '2025-01-15', antonyms: ['μαύρος'] },
    { id: 'el:mayro:adjective', word: 'μαύρος', language: 'el', form: 'adjective', level: 'A1', transcription: '/ˈmavros/', emoji: '⚫', definitions: ['που έχει το χρώμα της νύχτας'], examples: ['Ο γάτος είναι μαύρος.'], domain: 'general', theme: 'colors', updated: '2025-01-15', antonyms: ['άσπρος'] },
    { id: 'el:kokkino:adjective', word: 'κόκκινος', language: 'el', form: 'adjective', level: 'A1', transcription: '/ˈkokinos/', emoji: '🔴', definitions: ['που έχει το χρώμα του αίματος'], examples: ['Φοράει κόκκινο μπλουζάκι.'], domain: 'general', theme: 'colors', updated: '2025-01-15', no_antonym: true },
    { id: 'el:mple:adjective', word: 'μπλε', language: 'el', form: 'adjective', level: 'A1', transcription: '/ble/', emoji: '🔵', definitions: ['που έχει το χρώμα της θάλασσας'], examples: ['Ο ουρανός είναι μπλε σήμερα.'], domain: 'general', theme: 'colors', updated: '2025-01-15', no_antonym: true },
    { id: 'el:prasino:adjective', word: 'πράσινος', language: 'el', form: 'adjective', level: 'A1', transcription: '/ˈprasinos/', emoji: '🟢', definitions: ['που έχει το χρώμα του γρασιδιού'], examples: ['Το γρασίδι είναι πράσινο.'], domain: 'general', theme: 'colors', updated: '2025-01-15', no_antonym: true },
    { id: 'el:kitrino:adjective', word: 'κίτρινος', language: 'el', form: 'adjective', level: 'A1', transcription: '/ˈkitrinos/', emoji: '🟡', definitions: ['που έχει το χρώμα του ήλιου'], examples: ['Το λεμόνι είναι κίτρινο.'], domain: 'general', theme: 'colors', updated: '2025-01-15', no_antonym: true },
    { id: 'el:portokali:adjective', word: 'πορτοκαλής', language: 'el', form: 'adjective', level: 'A1', transcription: '/portokaˈlis/', emoji: '🟠', definitions: ['που έχει το χρώμα του πορτοκαλιού'], examples: ['Το πορτοκάλι είναι πορτοκαλί.'], domain: 'general', theme: 'colors', updated: '2025-01-15', no_antonym: true },
    { id: 'el:roz:adjective', word: 'ροζ', language: 'el', form: 'adjective', level: 'A1', transcription: '/roz/', emoji: '🩷', definitions: ['ανοιχτό κόκκινο χρώμα'], examples: ['Αγόρασε μια ροζ τσάντα.'], domain: 'general', theme: 'colors', updated: '2025-01-15', no_antonym: true },
    { id: 'el:kafe:adjective', word: 'καφέ', language: 'el', form: 'adjective', level: 'A1', transcription: '/kaˈfe/', emoji: '🟤', definitions: ['που έχει το χρώμα του καφέ'], examples: ['Ο σκύλος είναι καφέ.'], domain: 'general', theme: 'colors', updated: '2025-01-15', no_antonym: true },
    { id: 'el:gktri:adjective', word: 'γκρι', language: 'el', form: 'adjective', level: 'A1', transcription: '/ɡri/', emoji: '🩶', definitions: ['ενδιάμεσο χρώμα μεταξύ άσπρου και μαύρου'], examples: ['Τα σύννεφα είναι γκρι.'], domain: 'general', theme: 'colors', updated: '2025-01-15', no_antonym: true },
    { id: 'el:mov:adjective', word: 'μωβ', language: 'el', form: 'adjective', level: 'A1', transcription: '/mov/', emoji: '🟣', definitions: ['χρώμα μεταξύ μπλε και κόκκινου'], examples: ['Το λουλούδι είναι μωβ.'], domain: 'general', theme: 'colors', updated: '2025-01-15', no_antonym: true },
    { id: 'el:chryso:adjective', word: 'χρυσός', language: 'el', form: 'adjective', level: 'A1', transcription: '/xriˈsos/', emoji: '🪙', definitions: ['που έχει το χρώμα του χρυσού'], examples: ['Φοράει ένα χρυσό δαχτυλίδι.'], domain: 'general', theme: 'colors', updated: '2025-01-15', no_antonym: true }
  ],

  family: [
    { id: 'el:mitera:noun', word: 'μητέρα', language: 'el', form: 'noun', level: 'A1', article: 'η', gender: 'feminine', countability: 'countable', plural_form: 'μητέρες', transcription: '/miˈtera/', emoji: '👩', definitions: ['η γυναίκα που έχει γεννήσει ένα παιδί'], examples: ['Η μητέρα μου μαγειρεύει νόστιμα.'], domain: 'general', theme: 'family', updated: '2025-01-15', no_antonym: true },
    { id: 'el:pateras:noun', word: 'πατέρας', language: 'el', form: 'noun', level: 'A1', article: 'ο', gender: 'masculine', countability: 'countable', plural_form: 'πατέρες', transcription: '/paˈteras/', emoji: '👨', definitions: ['ο άνδρας που έχει παιδί'], examples: ['Ο πατέρας μου εργάζεται σκληρά.'], domain: 'general', theme: 'family', updated: '2025-01-15', no_antonym: true },
    { id: 'el:goneis:noun', word: 'γονείς', language: 'el', form: 'noun', level: 'A1', article: 'οι', gender: 'masculine', countability: 'pluralia_tantum', transcription: '/ɣoˈnis/', emoji: '🧑‍🧑‍🧒', definitions: ['η μητέρα και ο πατέρας μαζί'], examples: ['Οι γονείς μου μένουν στην Αθήνα.'], domain: 'general', theme: 'family', updated: '2025-01-15', no_antonym: true },
    { id: 'el:gios:noun', word: 'γιος', language: 'el', form: 'noun', level: 'A1', article: 'ο', gender: 'masculine', countability: 'countable', plural_form: 'γιοι', transcription: '/ʝos/', emoji: '👦', definitions: ['το αρσενικό παιδί μιας οικογένειας'], examples: ['Ο γιος τους πηγαίνει στο σχολείο.'], domain: 'general', theme: 'family', updated: '2025-01-15', no_antonym: true },
    { id: 'el:kori:noun', word: 'κόρη', language: 'el', form: 'noun', level: 'A1', article: 'η', gender: 'feminine', countability: 'countable', plural_form: 'κόρες', transcription: '/ˈkori/', emoji: '👧', definitions: ['το θηλυκό παιδί μιας οικογένειας'], examples: ['Η κόρη της είναι πολύ έξυπνη.'], domain: 'general', theme: 'family', updated: '2025-01-15', no_antonym: true },
    { id: 'el:paidi:noun', word: 'παιδί', language: 'el', form: 'noun', level: 'A1', article: 'το', gender: 'neuter', countability: 'countable', plural_form: 'παιδιά', transcription: '/peˈði/', emoji: '🧒', definitions: ['νεαρό αεροδιάγραμμα ή τέκνο'], examples: ['Το παιδί παίζει στο πάρκο.'], domain: 'general', theme: 'family', updated: '2025-01-15', no_antonym: true },
    { id: 'el:adelfos:noun', word: 'αδελφός', language: 'el', form: 'noun', level: 'A1', article: 'ο', gender: 'masculine', countability: 'countable', plural_form: 'αδελφοί', transcription: '/aðelˈfos/', emoji: '👦', definitions: ['αρσενικό τέκνο των ίδιων γονέων'], examples: ['Ο αδελφός μου είναι μεγαλύτερος.'], domain: 'general', theme: 'family', updated: '2025-01-15', no_antonym: true },
    { id: 'el:adelfi:noun', word: 'αδελφή', language: 'el', form: 'noun', level: 'A1', article: 'η', gender: 'feminine', countability: 'countable', plural_form: 'αδελφές', transcription: '/aðelˈfi/', emoji: '👧', definitions: ['θηλυκό τέκνο των ίδιων γονέων'], examples: ['Η αδελφή μου διαβάζει βιβλίο.'], domain: 'general', theme: 'family', updated: '2025-01-15', no_antonym: true },
    { id: 'el:giagia:noun', word: 'γιαγιά', language: 'el', form: 'noun', level: 'A1', article: 'η', gender: 'feminine', countability: 'countable', plural_form: 'γιαγιάδες', transcription: '/ʝaˈʝa/', emoji: '👵', definitions: ['η μητέρα του πατέρα ή της μητέρας'], examples: ['Η γιαγιά φτιάχνει νόστιμη πίτα.'], domain: 'general', theme: 'family', updated: '2025-01-15', no_antonym: true },
    { id: 'el:pappoys:noun', word: 'παππούς', language: 'el', form: 'noun', level: 'A1', article: 'ο', gender: 'masculine', countability: 'countable', plural_form: 'παππούδες', transcription: '/paˈpus/', emoji: '👴', definitions: ['ο πατέρας του πατέρα ή της μητέρας'], examples: ['Ο παππούς λέει ωραίες ιστορίες.'], domain: 'general', theme: 'family', updated: '2025-01-15', no_antonym: true },
    { id: 'el:syzygos-andras:noun', word: 'σύζυγος', language: 'el', form: 'noun', level: 'A1', article: 'ο', gender: 'masculine', countability: 'countable', plural_form: 'σύζυγοι', transcription: '/ˈsiziɣos/', emoji: '👨', definitions: ['ο άνδρας με τον οποίο είναι κανείς παντρεμένος'], examples: ['Ο σύζυγός της είναι γιατρός.'], domain: 'general', theme: 'family', updated: '2025-01-15', no_antonym: true },
    { id: 'el:syzygos-gynaika:noun', word: 'σύζυγος', language: 'el', form: 'noun', level: 'A1', article: 'η', gender: 'feminine', countability: 'countable', plural_form: 'σύζυγοι', transcription: '/ˈsiziɣos/', emoji: '👩', definitions: ['η γυναίκα με την οποία είναι κανείς παντρεμένος'], examples: ['Η σύζυγός του εργάζεται στο τραπεζικό κατάστημα.'], domain: 'general', theme: 'family', updated: '2025-01-15', no_antonym: true },
    { id: 'el:oikogeneia:noun', word: 'οικογένεια', language: 'el', form: 'noun', level: 'A1', article: 'η', gender: 'feminine', countability: 'countable', plural_form: 'οικογένειες', transcription: '/ikoˈjenia/', emoji: '👨‍👩‍👧‍👦', definitions: ['σύνολο ανθρώπων που συνδέονται με συγγένεια'], examples: ['Έχουμε μεγάλη και αγαπημένη οικογένεια.'], domain: 'general', theme: 'family', updated: '2025-01-15', no_antonym: true },
    { id: 'el:theios:noun', word: 'θείος', language: 'el', form: 'noun', level: 'A1', article: 'ο', gender: 'masculine', countability: 'countable', plural_form: 'θείοι', transcription: '/ˈθios/', emoji: '🧔', definitions: ['ο αδελφός του πατέρα ή της μητέρας'], examples: ['Ο θείος μου μένει στη Θεσσαλονίκη.'], domain: 'general', theme: 'family', updated: '2025-01-15', no_antonym: true },
    { id: 'el:theia:noun', word: 'θεία', language: 'el', form: 'noun', level: 'A1', article: 'η', gender: 'feminine', countability: 'countable', plural_form: 'θείες', transcription: '/ˈθia/', emoji: '👩', definitions: ['η αδελφή του πατέρα ή της μητέρας'], examples: ['Η θεία μου μας επισκέπτεται συχνά.'], domain: 'general', theme: 'family', updated: '2025-01-15', no_antonym: true },
    { id: 'el:xadelfos:noun', word: 'ξάδελφος', language: 'el', form: 'noun', level: 'A1', article: 'ο', gender: 'masculine', countability: 'countable', plural_form: 'ξάδελφοι', transcription: '/ˈksaðelfos/', emoji: '🧑', definitions: ['το παιδί του θείου ή της θείας'], examples: ['Ο ξάδελφός μου παίζει ποδόσφαιρο.'], domain: 'general', theme: 'family', updated: '2025-01-15', no_antonym: true },
    { id: 'el:moro:noun', word: 'μωρό', language: 'el', form: 'noun', level: 'A1', article: 'το', gender: 'neuter', countability: 'countable', plural_form: 'μωρά', transcription: '/moˈro/', emoji: '👶', definitions: ['πολύ μικρό βρέφος'], examples: ['Το μωρό κοιμάται στο κρεβάτι.'], domain: 'general', theme: 'family', updated: '2025-01-15', no_antonym: true },
    { id: 'el:andras:noun', word: 'άνδρας', language: 'el', form: 'noun', level: 'A1', article: 'ο', gender: 'masculine', countability: 'countable', plural_form: 'άνδρες', transcription: '/ˈandras/', emoji: '👨', definitions: ['ενήλικος άνθρωπος αρσενικού γένους'], examples: ['Ο άνδρας περπατάει στον δρόμο.'], domain: 'general', theme: 'family', updated: '2025-01-15', no_antonym: true },
    { id: 'el:gynaika:noun', word: 'γυναίκα', language: 'el', form: 'noun', level: 'A1', article: 'η', gender: 'feminine', countability: 'countable', plural_form: 'γυναίκες', transcription: '/ʝiˈneka/', emoji: '👩', definitions: ['ενήλικος άνθρωπος θηλυκού γένους'], examples: ['Η γυναίκα διαβάζει εφημερίδα.'], domain: 'general', theme: 'family', updated: '2025-01-15', no_antonym: true },
    { id: 'el:filos:noun', word: 'φίλος', language: 'el', form: 'noun', level: 'A1', article: 'ο', gender: 'masculine', countability: 'countable', plural_form: 'φίλοι', transcription: '/ˈfilos/', emoji: '🧑‍🤝‍🧑', definitions: ['πρόσωπο με το οποίο συνδέεται κανείς με φιλία'], examples: ['Ο φίλος μου με βοηθάει πάντα.'], domain: 'general', theme: 'family', updated: '2025-01-15', no_antonym: true }
  ],

  expressions: [
    { id: 'el:geia-sou:phrase', word: 'γεια σου', language: 'el', form: 'phrase', level: 'A1', transcription: '/ˈja su/', emoji: '👋', definitions: ['φιλικός χαιρετισμός κατά την συνάντηση'], examples: ['Γεια σου, τι κάνεις σήμερα;'], domain: 'general', theme: 'expressions', updated: '2025-01-15', no_antonym: true },
    { id: 'el:antio:phrase', word: 'αντίο', language: 'el', form: 'phrase', level: 'A1', transcription: '/anˈtio/', emoji: '👋', definitions: ['έκφραση αποχαιρετισμού'], examples: ['Αντίο, τα λέμε αύριο.'], domain: 'general', theme: 'expressions', updated: '2025-01-15', no_antonym: true },
    { id: 'el:parakalo:phrase', word: 'παρακαλώ', language: 'el', form: 'phrase', level: 'A1', transcription: '/parakaˈlo/', emoji: '🙏', definitions: ['λέξη ευγένειας όταν ζητάμε κάτι'], examples: ['Έναν καφέ παρακαλώ.'], domain: 'general', theme: 'expressions', updated: '2025-01-15', no_antonym: true },
    { id: 'el:efcharisto:phrase', word: 'ευχαριστώ', language: 'el', form: 'phrase', level: 'A0', transcription: '/efxarisˈto/', emoji: '🙏', definitions: ['έκφραση ευγνωμοσύνης'], examples: ['Ευχαριστώ πολύ για τη βοήθεια.'], domain: 'general', theme: 'expressions', updated: '2025-01-15', no_antonym: true },
    { id: 'el:parakalo-welcome:phrase', word: 'παρακαλώ', language: 'el', form: 'phrase', level: 'A0', transcription: '/parakaˈlo/', emoji: '👍', definitions: ['ευγενική απάντηση στο ευχαριστώ'], examples: ['Παρακαλώ, δεν κάνει τίποτα!'], domain: 'general', theme: 'expressions', updated: '2025-01-15', no_antonym: true },
    { id: 'el:nai:phrase', word: 'ναι', language: 'el', form: 'phrase', level: 'A1', transcription: '/ne/', emoji: '✅', definitions: ['λέξη κατάφασης'], examples: ['Ναι, θέλω έναν καφέ.'], domain: 'general', theme: 'expressions', updated: '2025-01-15', antonyms: ['όχι'] },
    { id: 'el:ochi:phrase', word: 'όχι', language: 'el', form: 'phrase', level: 'A1', transcription: '/ˈoxi/', emoji: '❌', definitions: ['λέξη άρνησης'], examples: ['Όχι, δεν μπορώ να έρθω.'], domain: 'general', theme: 'expressions', updated: '2025-01-15', antonyms: ['ναι'] },
    { id: 'el:me-synchoreite:phrase', word: 'με συγχωρείτε', language: 'el', form: 'phrase', level: 'A0', transcription: '/me siŋxoˈrite/', emoji: '🙋‍♂️', definitions: ['έκφραση για να ζητήσουμε συγγνώμη ή την προσοχή'], examples: ['Με συγχωρείτε, πού είναι ο σταθμός;'], domain: 'general', theme: 'expressions', updated: '2025-01-15', no_antonym: true },
    { id: 'el:syggnomi:phrase', word: 'συγγνώμη', language: 'el', form: 'phrase', level: 'A1', transcription: '/siˈɣnomi/', emoji: '🙇‍♂️', definitions: ['λέξη απολογίας για ένα λάθος'], examples: ['Συγγνώμη για την καθυστέρηση.'], domain: 'general', theme: 'expressions', updated: '2025-01-15', no_antonym: true },
    { id: 'el:kalimera:phrase', word: 'καλημέρα', language: 'el', form: 'phrase', level: 'A1', transcription: '/kalimeˈra/', emoji: '🌅', definitions: ['πρωινός χαιρετισμός'], examples: ['Καλημέρα, τι κάνετε σήμερα;'], domain: 'general', theme: 'expressions', updated: '2025-01-15', no_antonym: true },
    { id: 'el:kalispera:phrase', word: 'καλησπέρα', language: 'el', form: 'phrase', level: 'A1', transcription: '/kalisˈpera/', emoji: '🌆', definitions: ['απογευματινός ή βραδινός χαιρετισμός'], examples: ['Καλησπέρα σε όλους τους φίλους.'], domain: 'general', theme: 'expressions', updated: '2025-01-15', no_antonym: true },
    { id: 'el:kalynychta:phrase', word: 'καληνύχτα', language: 'el', form: 'phrase', level: 'A1', transcription: '/kaliniˈxta/', emoji: '🌙', definitions: ['ευχή πριν τον ύπνο'], examples: ['Καληνύχτα, γλυκά όνειρα!'], domain: 'general', theme: 'expressions', updated: '2025-01-15', no_antonym: true },
    { id: 'el:pos-eisai:phrase', word: 'πώς είσαι;', language: 'el', form: 'phrase', level: 'A0', transcription: '/pos ˈise/', emoji: '❓', definitions: ['ερώτηση για την κατάσταση κάποιου'], examples: ['Γεια σου Μαρία, πώς είσαι;'], domain: 'general', theme: 'expressions', updated: '2025-01-15', no_antonym: true },
    { id: 'el:charika:phrase', word: 'χάρηκα', language: 'el', form: 'phrase', level: 'A0', transcription: '/ˈxarika/', emoji: '🤝', definitions: ['έκφραση ευχαρίστησης κατά τη γνωριμία'], examples: ['Χάρηκα πολύ για τη γνωριμία.'], domain: 'general', theme: 'expressions', updated: '2025-01-15', no_antonym: true },
    { id: 'el:kalos-orises:phrase', word: 'καλώς όρισες', language: 'el', form: 'phrase', level: 'A1', transcription: '/kaˈlos ˈorises/', emoji: '🙋‍♀️', definitions: ['φιλόξονος χαιρετισμός σε κάποιον που φτάνει'], examples: ['Καλώς όρισες στο σπίτι μας!'], domain: 'general', theme: 'expressions', updated: '2025-01-15', no_antonym: true }
  ],

  pronouns: [
    { id: 'el:ti:phrase', word: 'τι', language: 'el', form: 'phrase', level: 'A1', transcription: '/ti/', emoji: '❓', definitions: ['ερωτηματική λέξη για πράγματα'], examples: ['Τι κάνεις αυτή τη στιγμή;'], domain: 'general', theme: 'pronouns', updated: '2025-01-15', no_antonym: true },
    { id: 'el:poios:pronoun', word: 'ποιος', language: 'el', form: 'pronoun', level: 'A1', transcription: '/pjos/', emoji: '❓', definitions: ['ερωτηματική αντωνυμία για πρόσωπα'], examples: ['Ποιος είναι αυτός ο άνδρας;'], domain: 'general', theme: 'pronouns', updated: '2025-01-15', no_antonym: true },
    { id: 'el:poy:pronoun', word: 'πού', language: 'el', form: 'pronoun', level: 'A1', transcription: '/pu/', emoji: '📍', definitions: ['ερωτηματική λέξη για τοποθεσία'], examples: ['Πού είναι το βιβλίο μου;'], domain: 'general', theme: 'pronouns', updated: '2025-01-15', no_antonym: true },
    { id: 'el:pote:adverb', word: 'πότε', language: 'el', form: 'adverb', level: 'A1', transcription: '/ˈpote/', emoji: '⏰', definitions: ['ερωτηματικό επίρρημα για χρόνο'], examples: ['Πότε φτάνει το τρένο;'], domain: 'general', theme: 'pronouns', updated: '2025-01-15', no_antonym: true },
    { id: 'el:giati:pronoun', word: 'γιατί', language: 'el', form: 'pronoun', level: 'A1', transcription: '/jaˈti/', emoji: '❓', definitions: ['ερωτηματική λέξη για την αιτία'], examples: ['Γιατί αργείς στο μάθημα;'], domain: 'general', theme: 'pronouns', updated: '2025-01-15', no_antonym: true },
    { id: 'el:pos:phrase', word: 'πώς', language: 'el', form: 'phrase', level: 'A1', transcription: '/pos/', emoji: '❓', definitions: ['ερωτηματική λέξη για τρόπο'], examples: ['Πώς σε λένε;'], domain: 'general', theme: 'pronouns', updated: '2025-01-15', no_antonym: true },
    { id: 'el:poso:pronoun', word: 'πόσο', language: 'el', form: 'pronoun', level: 'A0', transcription: '/ˈposo/', emoji: '🔢', definitions: ['ερωτηματική λέξη για ποσότητα ή τιμή'], examples: ['Πόσο κάνει αυτό το βιβλίο;'], domain: 'general', theme: 'pronouns', updated: '2025-01-15', no_antonym: true },
    { id: 'el:poio:pronoun', word: 'ποιο', language: 'el', form: 'pronoun', level: 'A1', transcription: '/pjo/', emoji: '❓', definitions: ['ερωτηματική αντωνυμία επιλογής'], examples: ['Ποιο βιβλίο θέλεις να διαβάσεις;'], domain: 'general', theme: 'pronouns', updated: '2025-01-15', no_antonym: true },
    { id: 'el:tinos:pronoun', word: 'τίνος', language: 'el', form: 'pronoun', level: 'A1', transcription: '/ˈtinos/', emoji: '❓', definitions: ['ερωτηματική αντωνυμία κτήσης'], examples: ['Τίνος είναι αυτό το στυλό;'], domain: 'general', theme: 'pronouns', updated: '2025-01-15', no_antonym: true },
    { id: 'el:poion:pronoun', word: 'ποιον', language: 'el', form: 'pronoun', level: 'A1', transcription: '/pjon/', emoji: '❓', definitions: ['ερωτηματική αντωνυμία αιτιατικής για πρόσωπα'], examples: ['Ποιον βλέπεις εκεί;'], domain: 'general', theme: 'pronouns', updated: '2025-01-15', no_antonym: true },
    { id: 'el:ego:pronoun', word: 'εγώ', language: 'el', form: 'pronoun', level: 'A1', transcription: '/eˈɣo/', emoji: '🙋‍♂️', definitions: ['προσωπική αντωνυμία πρώτου προσώπου'], examples: ['Εγώ μένω στην Αθήνα.'], domain: 'general', theme: 'pronouns', updated: '2025-01-15', no_antonym: true },
    { id: 'el:esy:pronoun', word: 'εσύ', language: 'el', form: 'pronoun', level: 'A1', transcription: '/eˈsi/', emoji: '🫵', definitions: ['προσωπική αντωνυμία δεύτερου προσώπου'], examples: ['Εσύ είσαι πολύ καλός φίλος.'], domain: 'general', theme: 'pronouns', updated: '2025-01-15', no_antonym: true },
    { id: 'el:aytos:pronoun', word: 'αυτός', language: 'el', form: 'pronoun', level: 'A1', transcription: '/afˈtos/', emoji: '👨', definitions: ['προσωπική αντωνυμία τρίτου προσώπου αρσενικού'], examples: ['Αυτός είναι ο καθηγητής μας.'], domain: 'general', theme: 'pronouns', updated: '2025-01-15', no_antonym: true },
    { id: 'el:ayti:pronoun', word: 'αυτή', language: 'el', form: 'pronoun', level: 'A1', transcription: '/afˈti/', emoji: '👩', definitions: ['προσωπική αντωνυμία τρίτου προσώπου θηλυκού'], examples: ['Αυτή είναι η μητέρα μου.'], domain: 'general', theme: 'pronouns', updated: '2025-01-15', no_antonym: true },
    { id: 'el:emeis:pronoun', word: 'εμείς', language: 'el', form: 'pronoun', level: 'A1', transcription: '/eˈmis/', emoji: '👥', definitions: ['προσωπική αντωνυμία πρώτου προσώπου πληθυντικού'], examples: ['Εμείς μαθαίνουμε ελληνικά.'], domain: 'general', theme: 'pronouns', updated: '2025-01-15', no_antonym: true },
    { id: 'el:eseis:pronoun', word: 'εσείς', language: 'el', form: 'pronoun', level: 'A1', transcription: '/eˈsis/', emoji: '👥', definitions: ['προσωπική αντωνυμία δεύτερου προσώπου πληθυντικού'], examples: ['Εσείς είστε από την Ελλάδα;'], domain: 'general', theme: 'pronouns', updated: '2025-01-15', no_antonym: true },
    { id: 'el:aytoi:pronoun', word: 'αυτοί', language: 'el', form: 'pronoun', level: 'A1', transcription: '/afˈti/', emoji: '👥', definitions: ['προσωπική αντωνυμία τρίτου προσώπου πληθυντικού'], examples: ['Αυτοί είναι οι φίλοι μας.'], domain: 'general', theme: 'pronouns', updated: '2025-01-15', no_antonym: true },
    { id: 'el:ayto:phrase', word: 'αυτό', language: 'el', form: 'phrase', level: 'A1', transcription: '/afˈto/', emoji: '👈', definitions: ['δεικτική αντωνυμία για κοντινό πράγμα'], examples: ['Αυτό είναι το σπίτι μου.'], domain: 'general', theme: 'pronouns', updated: '2025-01-15', no_antonym: true },
    { id: 'el:ekeino:phrase', word: 'εκείνο', language: 'el', form: 'phrase', level: 'A1', transcription: '/eˈkino/', emoji: '👉', definitions: ['δεικτική αντωνυμία για μακρινό πράγμα'], examples: ['Εκείνο το αυτοκίνητο είναι κόκκινο.'], domain: 'general', theme: 'pronouns', updated: '2025-01-15', no_antonym: true },
    { id: 'el:moy:pronoun', word: 'μου', language: 'el', form: 'pronoun', level: 'A1', transcription: '/mu/', emoji: '👤', definitions: ['κτητική αντωνυμία πρώτου προσώπου'], examples: ['Αυτό είναι το βιβλίο μου.'], domain: 'general', theme: 'pronouns', updated: '2025-01-15', no_antonym: true },
    { id: 'el:soy:pronoun', word: 'σου', language: 'el', form: 'pronoun', level: 'A1', transcription: '/su/', emoji: '👤', definitions: ['κτητική αντωνυμία δεύτερου προσώπου'], examples: ['Πού είναι το τσάντα σου;'], domain: 'general', theme: 'pronouns', updated: '2025-01-15', no_antonym: true },
    { id: 'el:mas:pronoun', word: 'μας', language: 'el', form: 'pronoun', level: 'A1', transcription: '/mas/', emoji: '👥', definitions: ['κτητική αντωνυμία πρώτου προσώπου πληθυντικού'], examples: ['Αυτό είναι το σπίτι μας.'], domain: 'general', theme: 'pronouns', updated: '2025-01-15', no_antonym: true }
  ],

  auxiliary_verbs: [
    { id: 'el:eimai:verb', word: 'είμαι', language: 'el', form: 'verb', level: 'A1', transcription: '/ˈime/', emoji: '👤', definitions: ['ρήμα ύπαρξης και ταυτότητας'], examples: ['Είμαι μαθητής στο σχολείο.'], domain: 'general', theme: 'auxiliary_verbs', updated: '2025-01-15', no_antonym: true },
    { id: 'el:echo:verb', word: 'έχω', language: 'el', form: 'verb', level: 'A1', transcription: '/ˈexo/', emoji: '🤲', definitions: ['ρήμα που δηλώνει κατοχή'], examples: ['Έχω ένα κόκκινο αυτοκίνητο.'], domain: 'general', theme: 'auxiliary_verbs', updated: '2025-01-15', no_antonym: true }
  ],

  feelings: [
    { id: 'el:charoymenos:adjective', word: 'χαρούμενος', language: 'el', form: 'adjective', level: 'A1', transcription: '/xaˈrumenos/', emoji: '😊', definitions: ['που νιώθει χαρά και ευτυχία'], examples: ['Είμαι πολύ χαρούμενος σήμερα.'], domain: 'general', theme: 'feelings', updated: '2025-01-15', antonyms: ['λυπημένος'] },
    { id: 'el:lypimenos:adjective', word: 'λυπημένος', language: 'el', form: 'adjective', level: 'A1', transcription: '/lipiˈmenos/', emoji: '😢', definitions: ['που νιώθει λύπη'], examples: ['Ο παιδί είναι λυπημένο σήμερα.'], domain: 'general', theme: 'feelings', updated: '2025-01-15', antonyms: ['χαρούμενος'] },
    { id: 'el:koyrasmenos:adjective', word: 'κουρασμένος', language: 'el', form: 'adjective', level: 'A1', transcription: '/kurasˈmenos/', emoji: '😫', definitions: ['που χρειάζεται ξεκούραση'], examples: ['Είμαι κουρασμένος μετά την εργασία.'], domain: 'general', theme: 'feelings', updated: '2025-01-15', no_antonym: true },
    { id: 'el:arrostos:adjective', word: 'άρρωστος', language: 'el', form: 'adjective', level: 'A1', transcription: '/ˈarostos/', emoji: '🤒', definitions: ['που δεν έχει καλή υγεία'], examples: ['Ο φίλος μου είναι άρρωστος.'], domain: 'general', theme: 'feelings', updated: '2025-01-15', no_antonym: true }
  ],

  general_adjectives: [
    { id: 'el:megalos:adjective', word: 'μεγάλος', language: 'el', form: 'adjective', level: 'A1', transcription: '/meˈɣalos/', emoji: '🐘', definitions: ['που έχει μεγάλες διαστάσεις'], examples: ['Αυτό το σπίτι είναι πολύ μεγάλο.'], domain: 'general', theme: 'general_adjectives', updated: '2025-01-15', antonyms: ['μικρός'] },
    { id: 'el:mikros:adjective', word: 'μικρός', language: 'el', form: 'adjective', level: 'A1', transcription: '/miˈkros/', emoji: '🐭', definitions: ['που έχει μικρές διαστάσεις'], examples: ['Βλέπω ένα μικρό πουλί.'], domain: 'general', theme: 'general_adjectives', updated: '2025-01-15', antonyms: ['μεγάλος'] },
    { id: 'el:psylos:adjective', word: 'ψηλός', language: 'el', form: 'adjective', level: 'A1', transcription: '/psiˈlos/', emoji: '🦒', definitions: ['που έχει μεγάλο ύψος'], examples: ['Ο αδελφός μου είναι πολύ ψηλός.'], domain: 'general', theme: 'general_adjectives', updated: '2025-01-15', antonyms: ['κοντός'] },
    { id: 'el:kontos:adjective', word: 'κοντός', language: 'el', form: 'adjective', level: 'A1', transcription: '/konˈtos/', emoji: '📏', definitions: ['που έχει μικρό ύψος'], examples: ['Το τραπέζι είναι κοντό.'], domain: 'general', theme: 'general_adjectives', updated: '2025-01-15', antonyms: ['ψηλός'] },
    { id: 'el:makrys:adjective', word: 'μακρύς', language: 'el', form: 'adjective', level: 'A1', transcription: '/maˈkris/', emoji: '📏', definitions: ['που έχει μεγάλο μήκος'], examples: ['Ο δρόμος είναι πολύ μακρύς.'], domain: 'general', theme: 'general_adjectives', updated: '2025-01-15', antonyms: ['κοντός'] },
    { id: 'el:grigoros:adjective', word: 'γρήγορος', language: 'el', form: 'adjective', level: 'A1', transcription: '/ˈɣriɣoros/', emoji: '⚡', definitions: ['που κινείται με μεγάλη ταχύτητα'], examples: ['Το αυτοκίνητο είναι πολύ γρήγορο.'], domain: 'general', theme: 'general_adjectives', updated: '2025-01-15', antonyms: ['αργός'] },
    { id: 'el:argos:adjective', word: 'αργός', language: 'el', form: 'adjective', level: 'A1', transcription: '/arˈɣos/', emoji: '🐢', definitions: ['που κινείται με μικρή ταχύτητα'], examples: ['Η χελώνα είναι αργό ζώο.'], domain: 'general', theme: 'general_adjectives', updated: '2025-01-15', antonyms: ['γρήγορος'] },
    { id: 'el:varys:adjective', word: 'βαρύς', language: 'el', form: 'adjective', level: 'A1', transcription: '/vaˈris/', emoji: '🏋️', definitions: ['που έχει μεγάλο βάρος'], examples: ['Αυτός ο σάκος είναι πολύ βαρύς.'], domain: 'general', theme: 'general_adjectives', updated: '2025-01-15', no_antonym: true }
  ],

  weather: [
    { id: 'el:ilios:noun', word: 'ήλιος', language: 'el', form: 'noun', level: 'A1', article: 'ο', gender: 'masculine', countability: 'countable', plural_form: 'ήλιοι', transcription: '/ˈilios/', emoji: '☀️', definitions: ['το ουράνιο σώμα που δίνει φως'], examples: ['Ο ήλιος λάμπει στον ουρανό.'], domain: 'general', theme: 'weather', updated: '2025-01-15', no_antonym: true },
    { id: 'el:feggari:noun', word: 'φεγγάρι', language: 'el', form: 'noun', level: 'A1', article: 'το', gender: 'neuter', countability: 'countable', plural_form: 'φεγγάρια', transcription: '/feˈɡari/', emoji: '🌙', definitions: ['ο φυσικός δορυφόρος της γης'], examples: ['Το φεγγάρι φωτίζει τη νύχτα.'], domain: 'general', theme: 'weather', updated: '2025-01-15', no_antonym: true },
    { id: 'el:vrochi:noun', word: 'βροχή', language: 'el', form: 'noun', level: 'A1', article: 'η', gender: 'feminine', countability: 'uncountable', transcription: '/vroˈxi/', emoji: '🌧️', definitions: ['νερό που πέφτει από τα σύννεφα'], examples: ['Η βροχή πέφτει δυνατά έξω.'], domain: 'general', theme: 'weather', updated: '2025-01-15', no_antonym: true },
    { id: 'el:chioni:noun', word: 'χιόνι', language: 'el', form: 'noun', level: 'A1', article: 'το', gender: 'neuter', countability: 'uncountable', transcription: '/ˈçoni/', emoji: '❄️', definitions: ['παγωμένος λευκός κρύσταλλος νερού'], examples: ['Το χιόνι καλύπτει το βουνό.'], domain: 'general', theme: 'weather', updated: '2025-01-15', no_antonym: true },
    { id: 'el:anemos:noun', word: 'άνεμος', language: 'el', form: 'noun', level: 'A1', article: 'ο', gender: 'masculine', countability: 'countable', plural_form: 'άνεμοι', transcription: '/ˈanemos/', emoji: '💨', definitions: ['το ρεύμα αέρα που φυσάει'], examples: ['Ο άνεμος είναι πολύ δυνατός.'], domain: 'general', theme: 'weather', updated: '2025-01-15', no_antonym: true },
    { id: 'el:synnefo:noun', word: 'σύννεφο', language: 'el', form: 'noun', level: 'A1', article: 'το', gender: 'neuter', countability: 'countable', plural_form: 'σύννεφα', transcription: '/ˈsinefo/', emoji: '☁️', definitions: ['λευκό ή γκρι σώμα στον ουρανό'], examples: ['Ένα λευκό σύννεφο καλύπτει τον ήλιο.'], domain: 'general', theme: 'weather', updated: '2025-01-15', no_antonym: true },
    { id: 'el:kairos:noun', word: 'καιρός', language: 'el', form: 'noun', level: 'A1', article: 'ο', gender: 'masculine', countability: 'uncountable', transcription: '/keˈros/', emoji: '🌤️', definitions: ['οι ατμοσφαιρικές συνθήκες μιας ημέρας'], examples: ['Ο καιρός είναι ζεστός σήμερα.'], domain: 'general', theme: 'weather', updated: '2025-01-15', no_antonym: true }
  ],

  geography: [
    { id: 'el:asteri:noun', word: 'αστέρι', language: 'el', form: 'noun', level: 'A1', article: 'το', gender: 'neuter', countability: 'countable', plural_form: 'αστέρια', transcription: '/asˈteri/', emoji: '🌟', definitions: ['φωτεινό ουράνιο σώμα τη νύχτα'], examples: ['Ένα αστέρι λάμπει στον ουρανό.'], domain: 'general', theme: 'geography', updated: '2025-01-15', no_antonym: true },
    { id: 'el:oyranos:noun', word: 'ουρανός', language: 'el', form: 'noun', level: 'A1', article: 'ο', gender: 'masculine', countability: 'countable', plural_form: 'ουρανοί', transcription: '/uraˈnos/', emoji: '🌌', definitions: ['ο χώρος πάνω από τη γη'], examples: ['Ο ουρανός είναι καθαρός και γαλάζιος.'], domain: 'general', theme: 'geography', updated: '2025-01-15', no_antonym: true },
    { id: 'el:thalassa:noun', word: 'θάλασσα', language: 'el', form: 'noun', level: 'A1', article: 'η', gender: 'feminine', countability: 'countable', plural_form: 'θάλασσες', transcription: '/ˈθalasa/', emoji: '🌊', definitions: ['μεγάλη έκταση αλμυρού νερού'], examples: ['Η ελληνική θάλασσα είναι πεντακάθαρη.'], domain: 'general', theme: 'geography', updated: '2025-01-15', no_antonym: true },
    { id: 'el:potami:noun', word: 'ποτάμι', language: 'el', form: 'noun', level: 'A1', article: 'το', gender: 'neuter', countability: 'countable', plural_form: 'ποτάμια', transcription: '/poˈtami/', emoji: '🏞️', definitions: ['μεγάλο ρεύμα γλυκού νερού'], examples: ['Το ποτάμι ρέει προς τη θάλασσα.'], domain: 'general', theme: 'geography', updated: '2025-01-15', no_antonym: true },
    { id: 'el:voyno:noun', word: 'βουνό', language: 'el', form: 'noun', level: 'A1', article: 'το', gender: 'neuter', countability: 'countable', plural_form: 'βουνά', transcription: '/vuˈno/', emoji: '⛰️', definitions: ['πολύ υψηλή ορεινή έκταση'], examples: ['Το βουνό έχει χιόνι στην κορυφή.'], domain: 'general', theme: 'geography', updated: '2025-01-15', no_antonym: true },
    { id: 'el:dasos:noun', word: 'δάσος', language: 'el', form: 'noun', level: 'A1', article: 'το', gender: 'neuter', countability: 'countable', plural_form: 'δάση', transcription: '/ˈðasos/', emoji: '🌲', definitions: ['μεγάλη έκταση γεμάτη δέντρα'], examples: ['Περπατάμε στο πράσινο δάσος.'], domain: 'general', theme: 'geography', updated: '2025-01-15', no_antonym: true },
    { id: 'el:dentro:noun', word: 'δέντρο', language: 'el', form: 'noun', level: 'A1', article: 'το', gender: 'neuter', countability: 'countable', plural_form: 'δέντρα', transcription: '/ˈðendro/', emoji: '🌳', definitions: ['ψηλό φυτό με ξύλινο κορμό'], examples: ['Το πουλί βρίσκεται στο δέντρο.'], domain: 'general', theme: 'geography', updated: '2025-01-15', no_antonym: true },
    { id: 'el:loyloydi:noun', word: 'λουλούδι', language: 'el', form: 'noun', level: 'A1', article: 'το', gender: 'neuter', countability: 'countable', plural_form: 'λουλούδια', transcription: '/luˈluði/', emoji: '🌸', definitions: ['το έγχρωμο μέρος ενός φυτού'], examples: ['Ένα όμορφο λουλούδι ανθίζει στον κήπο.'], domain: 'general', theme: 'geography', updated: '2025-01-15', no_antonym: true },
    { id: 'el:grasidi:noun', word: 'γρασίδι', language: 'el', form: 'noun', level: 'A1', article: 'το', gender: 'neuter', countability: 'uncountable', transcription: '/ɡraˈsiði/', emoji: '🌿', definitions: ['πράσινο χόρτο που καλύπτει το έδαφος'], examples: ['Τα παιδιά παίζουν στο γρασίδι.'], domain: 'general', theme: 'geography', updated: '2025-01-15', no_antonym: true },
    { id: 'el:petra:noun', word: 'πέτρα', language: 'el', form: 'noun', level: 'A1', article: 'η', gender: 'feminine', countability: 'countable', plural_form: 'πέτρες', transcription: '/ˈpetra/', emoji: '🪨', definitions: ['σκληρό πέτρωμα από το έδαφος'], examples: ['Έριξε μια πέτρα στο νερό.'], domain: 'general', theme: 'geography', updated: '2025-01-15', no_antonym: true },
    { id: 'el:gi:noun', word: 'γη', language: 'el', form: 'noun', level: 'A1', article: 'η', gender: 'feminine', countability: 'uncountable', transcription: '/ji/', emoji: '🌍', definitions: ['ο πλανήτης στον οποίο ζούμε'], examples: ['Η γη γυρίζει γύρω από τον ήλιο.'], domain: 'general', theme: 'geography', updated: '2025-01-15', no_antonym: true },
    { id: 'el:fotia:noun', word: 'φωτιά', language: 'el', form: 'noun', level: 'A1', article: 'η', gender: 'feminine', countability: 'countable', plural_form: 'φωτιές', transcription: '/foˈtia/', emoji: '🔥', definitions: ['φως και θερμότητα από καύση'], examples: ['Ανάψαμε φωτιά στο τζάκι.'], domain: 'general', theme: 'geography', updated: '2025-01-15', no_antonym: true },
    { id: 'el:aeras:noun', word: 'αέρας', language: 'el', form: 'noun', level: 'A1', article: 'ο', gender: 'masculine', countability: 'uncountable', transcription: '/aˈeras/', emoji: '💨', definitions: ['το μίγμα αερίων της ατμόσφαιρας'], examples: ['Ο καθαρός αέρας κάνει καλό.'], domain: 'general', theme: 'geography', updated: '2025-01-15', no_antonym: true }
  ]
};
